# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_attack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='oldpeak',
            field=models.FloatField(),
        ),
    ]
