# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_attack', '0002_auto_20180320_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedata',
            old_name='Chol',
            new_name='chol',
        ),
    ]
