# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_attack', '0003_auto_20180320_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedata',
            old_name='slpe',
            new_name='slope',
        ),
    ]
