# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart_attack', '0005_tempstorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='ads',
        ),
    ]
