# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heart_attack', '0006_remove_storedata_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
